# Generated by Django 4.2.2 on 2023-06-20 11:31

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("forecast", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forecast",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="updated")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("date", models.DateField(verbose_name="Denotes the measurement date")),
                (
                    "temperature",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(70)],
                        verbose_name="Temperature value for the day",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="No extra information for this day.",
                        verbose_name="Explicit description for the day",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="UserAccount",
        ),
    ]
